version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    restart: always

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=https://yazidjfktsgldczypybw.supabase.co
    restart: always
