version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=https://yazidjfktsgldczypybw.supabase.co
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "80"
    restart: always

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/1pa1.xyz:/etc/letsencrypt/live/1pa1.xyz:ro
      - /etc/letsencrypt/archive/1pa1.xyz:/etc/letsencrypt/archive/1pa1.xyz:ro
    restart: always
